name: Build

on: [workflow_dispatch, pull_request]

jobs:
  build:
    name: Create iOS simulator injection bundle
    runs-on: macos-12

    steps:
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1.4.0
      with:
        xcode-version: '13.4.1'

    - name: Checkout repo
      uses: actions/checkout@v2
      with: 
        submodules: 'recursive'


    - name: Build
      run: |-
        set -o pipefail
        mkdir output
        xcodebuild CODE_SIGNING_ALLOWED=NO -project InjectionIII.xcodeproj -scheme InjectionIII -config Release 2>&1 | tee output/build_log.txt
        injection_app_path=$(xcodebuild -config Release -showBuildSettings | grep "CODESIGNING_FOLDER_PATH" | cut -f2 -d'=' | tr -d ' ')
        rsync -au "$injection_app_path/Contents/Resources/iOSInjection.bundle" output/ 
        zip --symlinks -r output/iOSInjection.bundle.zip output/iOSInjection.bundle

    - name: Upload bundle
      uses: actions/upload-artifact@v2
      with:
        name: iOSInjection.bundle.zip
        path: output/iOSInjection.bundle.zip

    - name: Upload logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: output/build_log.txt

